### ISSUE TITLE
"Passing" injections to view partials

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/yii-view#40]
В данный момент view-injections работают только  с корневым view-файлом отрендеренном в контроллере и не работают в дочерних. Было-бы логично автоматически пробрасывать их и в дочерние

**Comment by terabytesoftw** [comment]
https://github.com/yiisoft/yii-view/blob/8c1d936fba7d352fe72909ac6f10380914aef1a8/src/CsrfViewInjection.php#L65 I could explain the case, you only have to pass the csrf in the secondary views of the layout and that is fine, but for all the other views rendered by the controller it is available without doing anything else, here it is injected to all of them.

**Comment by Gerych1984** [comment]
> https://github.com/yiisoft/yii-view/blob/8c1d936fba7d352fe72909ac6f10380914aef1a8/src/CsrfViewInjection.php#L63
> 
> I could explain the case, you only have to pass the `csrf` in the secondary views of the `layout` and that is fine, but for all the other views rendered by the controller it is available without doing anything else, here it is injected to all of them.

Yes. I have such structure of view files:

1. tab.php  // $csrf variabled exists, but it not needed here 
1.1_source_form.php // $csrf variable not exists
1.2 _links_form.php  // $csrf variabled not exists

So i propose injections inject own varialbes to every view file without set it in top level view

**Comment by samdark** [comment]
How do you render `_source_form.php` and `_links_form.php`?

**Comment by Gerych1984** [comment]
> How do you render `_source_form.php` and `_links_form.php`?

Просто вызываю в tabs.php $this->render(_source_form.php, [***]) и $this->render(_links_form.php, [***]), соотв. форма на каждый таб.
