### ISSUE TITLE
WebView registerJs/registerScriptTag не добавляют своё содержимое

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/yii-view#42]
| Q                | A
| ---------------- | ---
| Version          | 2.0.1

После обновления до версии 2.0.1 WebView перестало рендерить в layout содержимое добавленное методами registerJs и т.д. в указанные места

**Comment by Gerych1984** [comment]
Доброго дня. Заработало после обновления до 3.0.0 - и $csrf и register***. Вопрос - а предполагается какая-то возможность получить во вью не строку $csrf, а весь объект? Т.е. сейчас простой hidden input в поле выглядит так
`<input type="hidden" name="_csrf" value="<?= $csrf ?>">`, что в принципе нормально пока по какой-то причине не понадобиться передавать не дефолтное имя поля (_csrf).
 Т.е. такой вариант `<input type="hidden" name="<?= $csrf->getParameterName() ?>" value="<?= $csrf->getValue() ?>">`

**Comment by vjik** [comment]
Передавать объект
